CREATE TABLE donations
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount      DOUBLE PRECISION,
    comission   DOUBLE PRECISION,
    daonated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id     INTEGER,
    shelter_id  INTEGER,
    CONSTRAINT pk_donations PRIMARY KEY (id)
);

CREATE TABLE pet_details
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed         VARCHAR(255),
    special_needs VARCHAR(255),
    CONSTRAINT pk_pet_details PRIMARY KEY (id)
);

CREATE TABLE pets
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    type      VARCHAR(255),
    available BOOLEAN,
    pet_id    INTEGER,
    owner_id  INTEGER,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE shelters
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    email       VARCHAR(255),
    location    VARCHAR(255),
    description VARCHAR(255),
    website     VARCHAR(255),
    CONSTRAINT pk_shelters PRIMARY KEY (id)
);

CREATE TABLE swipes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status  VARCHAR(255),
    user_id INTEGER,
    pet_id  INTEGER,
    CONSTRAINT pk_swipes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    location VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE pets
    ADD CONSTRAINT uc_pets_pet UNIQUE (pet_id);

ALTER TABLE shelters
    ADD CONSTRAINT uc_shelters_email UNIQUE (email);

ALTER TABLE shelters
    ADD CONSTRAINT uc_shelters_website UNIQUE (website);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_SHELTER FOREIGN KEY (shelter_id) REFERENCES shelters (id);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES shelters (id);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_PET FOREIGN KEY (pet_id) REFERENCES pet_details (id);

ALTER TABLE swipes
    ADD CONSTRAINT FK_SWIPES_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE swipes
    ADD CONSTRAINT FK_SWIPES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);